name: Sonar
on:
  push: { branches: [ main, master ] }
  pull_request:
jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - run: npm i -g yarn
      - run: mvn -T1C -B clean install -DskipTests -DskipITs
      - run: mvn -B org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=hadisrjn_thingsboard -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=<org> -Dsonar.login=${{ secrets.SONAR_TOKEN }}
